mov_pjt/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    # path('password/', views.change_password, name='change_password'),
] 

mov_pjt/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update', views.update, name='update'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:movies_pk>/comments/<int:comments_pk>/delete', views.comments_delete, name='comments_delete'),
    path('<int:movies_pk>/likes/', views.likes, name='likes'),
]

mov_pjt/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

mov_pjt/movies/models.py
from random import choices
from django.db import models
from django.conf import settings
# Create your models here.

class Movie(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=20)
    audience = models.IntegerField()
    release_date = models.DateField(auto_now_add=False)
    genre_Choice = (('Comedy','Comedy'),('Action','Action'),('Romance','Romance'),('Adventure','Adventure'),('Crime','Crime'),('War','War'),('Drama','Drama'),('Horror','Horror'),('Science Fiction ','Science Fiction '),('Musicals','Musicals'),('Historical','Historical'))
    genre = models.CharField(max_length=20, choices=genre_Choice)
    score = models.FloatField()
    poster_url = models.TextField()
    description = models.TextField()
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='likes_movies')

    def __str__(self):
        return self.title


class Comment(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    comment = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comment

mov_pjt/movies/forms.py
from tkinter import Widget
from django import forms
from .models import Movie, Comment

class MovieForm(forms.ModelForm):

    title = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Title'}))
    audience = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Audience'}))
    score = forms.FloatField(required=False, max_value=5, min_value=0,
        widget=forms.NumberInput(attrs={'id':'form_homework', 'step':"0.5", 'placeholder':'Score', 'class':'field-row','style':"width: 50px;"}))
    poster_url = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Poster url', 'class':'form-control'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'placeholder':'Descrition'}))
    release_date = forms.DateField(
    #     widget=forms.DateInput(
    #         attrs = {
    #             'class':'form-control', 
    #             'placeholder':'Select a date', 
    #             'type':'date',
    #             'style':"width: 200px;",
    #         }
    #     )
    )   
    
    class Meta:
        model = Movie
        fields = '__all__'
        exclude = ('user',)
        

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        # fields = '__all__'
        exclude = ('movie', 'user',)

mov_pjt/movies/views.py
from django.shortcuts import render, redirect
from .models import Movie, Comment
from .forms import MovieForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST, require_safe

# Create your views here.


def index(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies,
        'title': "Best Film Archive",
    }
    return render(request, 'movies/index.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save(commit=False)
            movie.user = request.user
            movie.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm()
    context = {
        'form': form,
        'title': "CREATE",
    }
    return render(request, 'movies/create.html', context)


@require_safe
def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    comment_form = CommentForm()
    comments = movie.comment_set.all()
    context = {
        'movie': movie,
        'comment_form': comment_form,
        'comments': comments,
        'title': "DETAIL",
    }
    return render(request, 'movies/detail.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def update(request, pk):
    movie = Movie.objects.get(pk=pk)
    if request.user == movie.user:
        if request.method == 'POST':
            form = MovieForm(request.POST, instance=movie)
            if form.is_valid():
                form.save()
                return redirect('movies:detail', movie.pk)
        else:
            form = MovieForm(instance = movie)
    else:
        return redirect('movies:index')
    
    context ={
        'form': form,
        'movie': movie,
        'title': "UPDATE",
    }
    return render(request, 'movies/update.html', context)


@login_required
@require_POST
def delete(request, pk):
    movie = Movie.objects.get(pk=pk)
    if request.user.is_authenticated:
        if request.user == movie.user:
            movie.delete()
            return redirect('movies:index')
    return redirect('movies:detail', movie.pk)


############################ 좋아요 ######################################
@require_POST
def likes(request, movies_pk):
    if request.user.is_authenticated:
        movie = Movie.objects.get(pk=movies_pk)

        if movie.like_users.filter(pk=request.user.pk).exists():
            movie.like_users.remove(request.user)
        else:
            movie.like_users.add(request.user)
        return redirect('movies:detail', movie.pk)
    return redirect('accounts:login')


############################# 코멘트 ######################################


@require_POST
def comments_create(request, pk):
    if request.user.is_authenticated:
        movie = Movie.objects.get(pk=pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.movie = movie
            comment.user = request.user
            comment.save()
        return redirect('movies:detail', movie.pk)
    return redirect('accounts:login')


@login_required
@require_POST
def comments_delete(request, movie_pk, comment_pk):
    if request.user.is_authenticated:
        comment = Comment.objects.get(pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    return redirect('movies:detail', movie_pk)

mov_pjt/movies/templates/movies/create.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'movies:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value='Submit' style="color: black; text-decoration-line: none; font-size: 16px; font-weight: bold;">
</form>
<hr>
<button type="button" onclick = "location.href = '{% url 'movies:index' %}'"><a style="color: black; text-decoration-line: none; font-size: 16px; font-weight: bold; padding-bottom: 20px" href = "{% url 'movies:index' %}">BACK</a></button><br>
{% endblock content %}

mov_pjt/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
<hr>
  <img src={{ movie.poster_url }} alt="" style = "height: 450px;">
<p>
  <div style="font-weight: bold; margin-left: 2px; font-size: 18px;">
<p style="font-weight: bold; font-size: 30px;">{{ movie.title }}</p>
<p>Audience: {{ movie.audience }}</p>
<p>Release Date: {{ movie.release_date }}</p>
<p>Genre: {{ movie.genre }}</p>
<p>Score: {{ movie.score }}</p>
<p>{{ movie.description }}</p>
  </div>
  <hr>
  <div>
    <form action= "{% url 'movies:likes' movie.pk %}" method="POST">
      {% csrf_token %}
      {% if request.user in movie.like_users.all %}
        <input type="submit" value="Dislike">
      {% else %}
        <input type="submit" value="Like">
      {% endif %}
    </form>
  </div>

  <hr>
  <button type="button" onclick = "location.href = '{% url 'movies:update' movie.pk %}'" style="color: black; text-decoration-line: none; font-size: 16px; font-weight: bold;">UPDATE</button>
<form action= "{% url 'movies:delete' movie.pk %}" method="POST">
  {% csrf_token %}
  <input style='font-size: 16px; font-weight: bold;' class="mt-1" type='submit' value='DELETE'>
</form>

<button type="button" onclick = "location.href = '{% url 'movies:index' %}'" style="color: black; text-decoration-line: none; font-size: 16px; font-weight: bold; margin-top: 5px;">BACK</button>
<hr>
<h3>Comments</h3>
{% if comments %}
  {% comment %} <p>{{ comments|length }}</p> {% endcomment %}
{% endif %}
  {% for comment in comments %}
    <li class="d-flex">
      {{ comment.user }} : {{ comment.comment }}
  
  {% endfor %}
    </li>
<div style='font-weight: bold;'>
{% if request.user.is_authenticated %}
    <form action="{% url 'movies:comments_create' movie.pk %}" method="POST" >
      {% csrf_token %}
      {{ comment_form }}
      <input type="submit" value='Submit'>
    </form>
  {% else %}
    <a href="{% url 'accounts:login' %}">댓글을 작성하려면 로그인 하세요.</a>
  {% endif %}
</div>

{% endblock content %}

mov_pjt/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}

<button class="mt-2" style="margin-left: 4px; text-decoration-line: none; color: black; font-weight: bold; font-size: 18px;" type="button" onclick = "location.href = '{% url 'movies:create' %}'">CREATE</button>
<hr>
<div style = "margin-left: 5px;">
{% for movie in movies  %}
<img src={{ movie.poster_url }} alt="" style = "height: 300px;" onclick = "location.href = '{% url 'movies:detail' movie.pk %}'" type="button"><br>
<button class="mt-2" type="button" onclick = "location.href = '{% url 'movies:detail' movie.pk %}'"><a style="font-weight: bold; font-size: 20px; color: black; text-decoration-line: none;">{{ movie.title }}</a></button>
<p  class="mt-2" style="font-weight: bold; margin-left: 2px; font-size: 18px;"> IMDB Rating: {{ movie.score }} </p>
</div>
<hr>
{% endfor %}
{% endblock content %}

mov_pjt/movies/templates/movies/update.html
{% extends 'base.html' %}

{% block content %}

<form action="{% url 'movies:update' movie.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value='Submit' style="color: black; text-decoration-line: none; font-size: 14px; font-weight: bold;">
    <input type="submit" value='Cancel' style="color: black; text-decoration-line: none; font-size: 14px; font-weight: bold;">
</form>
<hr>
{% endblock content %}