mov_pjt/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    # path('password/', views.change_password, name='change_password'),
] 

mov_pjt/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

mov_pjt/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Film World</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous"> 
    <link rel="stylesheet" href="https://unpkg.com/98.css" />
    <style>
        body {
            background-color: lightgrey;
        }

        .top {
          color: black; text-decoration-line: none; position: fixed; font-size: 0.7rem;
        }

    </style>
</head>
<body>
  
    <div class="title-bar">
        <div class="title-bar-text" style = "text-align: center; color: white;">
          <div class="d-flex justify-content-center">
            <h1>{{ title }}</h1>
          </div>
        </div>
      </div>
        
        {% if request.user.is_authenticated %}
        <div style="right: 1.5rem; top: 2rem; position: fixed; font-size: 1rem; font-weight: bold;">
          Welcome! {{ user }}
        </div>
          <form action="{% url 'accounts:logout' %}" method="POST" style="right:15rem; top: 2rem; position: fixed; font-size: 0.7rem;">
            {% csrf_token %}
            <input type="submit" value="Logout">
          </form>
          
          <button type="button" onclick = "location.href = '{% url 'accounts:update' %}'" style="color: black; text-decoration-line: none; right:10rem; top: 2rem; position: fixed; font-size: 0.7rem;">UPDATE</button>
        {% else %}

        <button type="button" onclick = "location.href = '{% url 'accounts:login' %}'" class = top style="right:15rem; top: 2rem; ">Login</button>
        <button type="button" onclick = "location.href = '{% url 'accounts:signup' %}'" class = top style="right:10rem; top: 2rem; ">Signup</button>
          
        {% endif %}
        
    <div style = "margin: 10px;">
    {% block content %}
    {% endblock content %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>